In [1]:
import pandas as pd
import numpy as np

### Lets create a model with 50 observations and 2 features per observation

In [2]:
feature_1=np.random.randint(low=1,high=20,size=(50,))
feature_2=np.random.randint(low=1,high=20,size=(50,)) 

In [3]:
feature_1.shape, feature_2.shape

((50,), (50,))

In [4]:
y_true=3+2*feature_1-4*feature_2+np.random.random((50,))
print(y_true.shape)
y_true 

(50,)


array([-40.81294687,   5.2775056 , -58.90611268,  27.65483219,
       -10.30624556, -28.77397269,  -0.56200162,   7.43895966,
         5.81864731, -22.17336313,  33.94718229, -18.14462105,
       -44.4432811 , -46.00759249,   3.27498733,  -8.87843768,
        -0.91123186,   3.26435488, -26.36147614,  -2.43466143,
         7.89466302, -16.49646426, -54.07988534,   1.65010991,
       -34.01911542, -14.90840741, -28.38952686, -50.01472853,
       -14.37166838, -26.90804472, -36.25352695,   3.5706758 ,
       -22.03077785,  -6.28635005, -22.4736583 , -22.28496038,
        -8.92289239,  11.2344773 ,  -8.43192721, -44.80371343,
        31.62661695, -40.15367846,  -4.91339842,  -0.12191303,
       -14.87474321, -52.038818  ,   7.14724749,  -2.94570421,
         1.29149807,  17.53431914])

In [6]:
X=pd.DataFrame({'intercept':np.ones_like(feature_1),'feature_1':feature_1,'feature_2':feature_2})
X.head()

intercept  feature_1  feature_2
0          1         14         18
1          1         19          9
2          1          1         16
3          1         18          3
4          1          5          6

In [7]:
W=np.zeros(X.shape[1])
W

array([0., 0., 0.])

In [8]:
def myprediction(features,weights):
    predictions=np.dot(features,weights)
    return(predictions)

y_pred = myprediction(X,W)
y_pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
def myerror(y_true,y_pred):
    error=y_true - y_pred
    return(error)
myerror(y_true,y_pred)

array([-40.81294687,   5.2775056 , -58.90611268,  27.65483219,
       -10.30624556, -28.77397269,  -0.56200162,   7.43895966,
         5.81864731, -22.17336313,  33.94718229, -18.14462105,
       -44.4432811 , -46.00759249,   3.27498733,  -8.87843768,
        -0.91123186,   3.26435488, -26.36147614,  -2.43466143,
         7.89466302, -16.49646426, -54.07988534,   1.65010991,
       -34.01911542, -14.90840741, -28.38952686, -50.01472853,
       -14.37166838, -26.90804472, -36.25352695,   3.5706758 ,
       -22.03077785,  -6.28635005, -22.4736583 , -22.28496038,
        -8.92289239,  11.2344773 ,  -8.43192721, -44.80371343,
        31.62661695, -40.15367846,  -4.91339842,  -0.12191303,
       -14.87474321, -52.038818  ,   7.14724749,  -2.94570421,
         1.29149807,  17.53431914])

In [10]:
def mycost(y_true,y_pred):
    error=myerror(y_true,y_pred)
    cost=np.dot(error.T,error)
    return(cost)

mycost(y_true,y_pred)

33771.258027026466

In [11]:
def gradient(y_true,features,weights):
    
    y_pred = myprediction(features,weights)
    error=myerror(y_true,y_pred)    
    gradient=-np.dot(features.T,error)  #gradient = -2X^T*(y-XW)
    
    return(gradient)

gradient(y_true,X,W)

array([  665.81377014,  2805.87063279, 10444.64742732])

In [15]:
def my_lr(y_true,features,learning_rate):
    
    weights=np.zeros(features.shape[1])
    
    for i in np.arange(10000):
        
        weights = weights - learning_rate*gradient(y_true,features,weights)         
#        weights[0] = weights[0] - 10*learning_rate*gradient(y_true,features,weights)[0]
        
        if i%1000==0:
            y_pred = myprediction(features,weights)
            print(mycost(y_true,y_pred),weights)
            
    return(weights)

my_lr(y_true,X,0.0001)

18261.533796117736 [-0.16479671 -0.28058706 -1.04446474]
4.445672941105757 [ 3.36795559  2.00435792 -3.98607983]
4.445671901150761 [ 3.36830334  2.00434344 -3.98609946]
4.445671901150771 [ 3.36830337  2.00434343 -3.98609946]
4.445671901150757 [ 3.36830337  2.00434343 -3.98609946]
4.445671901150757 [ 3.36830337  2.00434343 -3.98609946]
4.445671901150757 [ 3.36830337  2.00434343 -3.98609946]
4.445671901150757 [ 3.36830337  2.00434343 -3.98609946]
4.445671901150757 [ 3.36830337  2.00434343 -3.98609946]
4.445671901150757 [ 3.36830337  2.00434343 -3.98609946]
4.445671901150757 [ 3.36830337  2.00434343 -3.98609946]
4.445671901150757 [ 3.36830337  2.00434343 -3.98609946]
4.445671901150757 [ 3.36830337  2.00434343 -3.98609946]
4.445671901150757 [ 3.36830337  2.00434343 -3.98609946]
4.445671901150757 [ 3.36830337  2.00434343 -3.98609946]
4.445671901150757 [ 3.36830337  2.00434343 -3.98609946]
4.445671901150757 [ 3.36830337  2.00434343 -3.98609946]
4.445671901150757 [ 3.36830337  2.00434343 -3.9

array([ 3.36830337,  2.00434343, -3.98609946])

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
lr=LinearRegression()

In [18]:
X.shape

(50, 3)

In [20]:
lr.fit(X.iloc[:,1:],y_true)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [21]:
lr.coef_

array([ 2.00434343, -3.98609946])

In [22]:
lr.intercept_

3.368303365437349