## Revision- Week1

In [2]:
from IPython.display import Image

import numpy as np
import pandas as pd

### 1. Write 2 `mutable` data-types of python:

### 2. Write 2 `immutable` data-types of python:

In [ ]:
Image(filename='../images/py_datatypes.png')

### Bullet Points 
 - every variable is Python is an **object instance**. 
 - When an object is created, it is assigned a unique **object id**. 
 - The type of that **object** is defined at **runtime** 
 - For an object, **object id can never change**
 - The **state** of that object **can be changed** if it is mutable. 
 - A **mutable** object can be changed after it is created, and an **immutable** object can’t be.    

In [ ]:
#case 1:
x = [1,2,3]
y = x
x.pop()

### 3. is id(x) == id(y) ?

In [ ]:
id(x) == id(y)

In [ ]:
#case 2:
x = 3; y = x; x = x +1

### 4. is id(x) == id(y) ?

In [ ]:
id(x), id(y)

In [ ]:
id(x) == id(y)

### 5. Find all errors in the function definition below <br>

In [ ]:
func add elems:(k=3,r)
x = r + k
return X

add elems(2,3)

### 6. Define a class:

Upon initialisation (`__init__`), the class should take a string from console input 

The class should have 2 methods: <br>
`get_upper`: to return the string in upper case. <br>
`get_lower`: to return the string in lower case.

In [3]:
s = InputOutString()

Enter a string:pRaDip


In [4]:
s.get_upper()

'PRADIP'

In [5]:
s.get_lower()

'pradip'

# Numpy Quick Recap

In [ ]:
Image(filename='../images/np_arrays.png')

### Bullent Points: NumPy Array
 1. _**Attributes of arrays**_: Determining the size, shape, memory consumption, and data types of arrays <br>
 `ndarray.size`   `ndarray.shape`   `ndarray.dtype`
 2. _**Indexing of arrays**_: Getting and setting the value of individual array elements <br>
 `array[r,c]`
 3. _**Slicing of arrays**_: Getting and setting smaller subarrays within a larger array <br>
 `array[start_row:end_row, start_col:end_col]` <br>
 `row_indices=[r1,r2,..]; col_indices=[c1,c2..]; array[row_indices, col_indices]`
 4. _**Reshaping of arrays**_: Changing the shape of a given array <br>
 `array.reshape(r,c)`
 5. _**Joining and splitting of arrays**_: Combining multiple arrays into one, and splitting one array into many <br>
 `np.vstack` `np.hstack` `np.tile`

In [ ]:
Image(filename='../images/np_broadcasting.png', width=800)

### 7. Using `lst` generate `arrint` as shown:

In [6]:
lst = [1,2,3,4.0]

In [8]:
array

array([1, 2, 3, 4], dtype=int32)

### 8. Write a function to generate a list of all even numbers between 0 to 100

### 9. Write the same function as a list comprehension

### 10. For the above function, return the output as a 2D array with 2 rows

### 11. What are the different attributes of an array?

### 12. Write 5 array generating functions: (like numpy.arange())

### 13. From array `a`, create array `b` as a deep copy:

In [9]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
b

array([[ 7],
       [11]])

### 14. Reshape arr into 2D array with 3 rows:

In [12]:
twoD_arr = np.arange(1, 46)

- The criterion to satisfy for providing the new shape is that _'The new shape should be compatible with the original shape'_
- numpy allow us to give one of new shape parameter as -1 (eg: (2,-1) or (-1,3) but not (-1, -1)). 
- It simply means that it is an unknown dimension and we want numpy to figure it out. And numpy will figure this by looking at the 'length of the array and remaining dimensions' and making sure it satisfies the above mentioned criteria

### 15. From the array `twenty` below, generate the `result` as shown

In [13]:
twenty = (np.arange(4 * 5)).reshape(4, 5)
twenty

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
result

array([ 6, 12, 19])

### 16. Using conditional statements, generate `result` from `range_arr` as shown:

In [16]:
range_arr = np.arange(0, 10, 0.5)
range_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [18]:
result

array([5.5, 6. , 6.5, 7. ])

### 17. Using array `a` and `b`, create `vs` and `hs` as shown:

In [19]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [20]:
b = np.array([[5, 6]])
b

array([[5, 6]])

In [23]:
vs

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
hs

array([[1, 2, 5],
       [3, 4, 6]])

### 18. From the given array, generate row wise and column wise average as shown:

In [25]:
arr = np.arange(5 * 6).reshape(5, 6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
 #column-wise

In [ ]:
 #row-wise

### 19. Show how to do this?

Suppose that X is a data matrix of shape `(n,p)`. That is, there are `n` data points and `p` features per point. Often, we have to remove the mean from each feature. That is, we want to compute the mean for each feature and then remove the mean from each column. 

In [ ]:
# say n =10, and p =30
n = 10
p = 30
X = np.random.rand(n,p)
X.shape

## Bonus Questions

## 1. Compute Eigen Value and Eigen Vectors

`A * eigen_vector — eigen_value * eigen_vector = 0`

In [26]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 2. Write a function to convert a list to dictionary as shown: 

`mylist = ['Zero', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine']`

`mydict = 
{
    0 : 'Zero',
    1 : 'One',
    2 : 'Two',
    3 : 'Three',
    4 : 'Four',
    5 : 'Five',
    6 : 'Six',
    7 : 'Seven',
    8 : 'Eight',
    9 : 'Nine',
}`

In [27]:
x = ['Zero', 'One', 'Two', 'Three', 'Four']

In [29]:
d = list_to_dict(x)
d

{0: 'Zero', 1: 'One', 2: 'Two', 3: 'Three', 4: 'Four'}

### 3. Binary Search

Given a sorted array arr[] of n elements, write a function to search a given element x in arr[].

A simple approach is to do linear search.The time complexity of above algorithm is O(n). Another approach to perform the same task is using Binary Search. 

In Binary search, we search a sorted array by repeatedly dividing the search interval in half. Begin with an interval covering the whole array. If the value of the search key is less than the item in the middle of the interval, narrow the interval to the lower half. Otherwise narrow it to the upper half. Repeatedly check until the value is found or the interval is empty.

In [31]:
# Test array 
arr = [ 2, 3, 4, 10, 40 ] 
x = 10
  
# Function call 
result = binarySearch(arr, 0, len(arr)-1, x) 
  
if result != -1: 
    print("Element is present at index %d" % result)
else: 
    print("Element is not present in array")

Element is present at index 3


### 4. Given a list of numbers, write a function to return outliers?

#### How are outliers defined?

Here we can assume that outliers are defined as numbers outside of `[Q1 - 1.5 * IQR, Q3 + 1.5 * IQR]`
where `Q1` is the first quartile, `Q3` is the third quartile, and `IQR` is the inner quartile range `(Q3 - Q1)`

The runtime of this algorithm is at least O(n), but potentially larger depending on how numpy computes quartiles.

In [33]:
L = [1,2,3,4,6,1,2,3,4,6,1,99,-100,1,2,3,4,5,2,2,22,34,1,2,3,4,-10]
findOutliers(L)

[99, -100, 22, 34, -10]