## Revision- Week1

In [ ]:
from IPython.display import Image

import numpy as np
import pandas as pd

### 1. Write 2 `mutable` data-types of python:

### 2. Write 2 `immutable` data-types of python:

In [ ]:
Image(filename='../images/py_datatypes.png')

### Bullet Points 
 - every variable is Python is an **object instance**. 
 - When an object is created, it is assigned a unique **object id**. 
 - The type of that **object** is defined at **runtime** 
 - For an object, **object id can never change**
 - The **state** of that object **can be changed** if it is mutable. 
 - A **mutable** object can be changed after it is created, and an **immutable** object can’t be.    

In [ ]:
#case 1:
x = [1,2,3]
y = x
x.pop()

### 3. is id(x) == id(y) ?

In [ ]:
id(x) == id(y)

In [ ]:
#case 2:
x = 3; y = x; x = x +1

### 4. is id(x) == id(y) ?

In [ ]:
id(x), id(y)

In [ ]:
id(x) == id(y)

### 5. Find all errors in the function definition below <br>

In [ ]:
func add elems:(k=3,r)
x = r + k
return X

add elems(2,3)

### 6. Define a class:

Upon initialisation (`__init__`), the class should take a string from console input 

The class should have 2 methods: <br>
`get_upper`: to return the string in upper case. <br>
`get_lower`: to return the string in lower case.

In [ ]:
s = InputOutString()

In [ ]:
s.get_upper()

In [ ]:
s.get_lower()

# Numpy Quick Recap

In [ ]:
Image(filename='../images/np_arrays.png')

### Bullent Points: NumPy Array
 1. _**Attributes of arrays**_: Determining the size, shape, memory consumption, and data types of arrays <br>
 `ndarray.size`   `ndarray.shape`   `ndarray.dtype`
 2. _**Indexing of arrays**_: Getting and setting the value of individual array elements <br>
 `array[r,c]`
 3. _**Slicing of arrays**_: Getting and setting smaller subarrays within a larger array <br>
 `array[start_row:end_row, start_col:end_col]` <br>
 `row_indices=[r1,r2,..]; col_indices=[c1,c2..]; array[row_indices, col_indices]`
 4. _**Reshaping of arrays**_: Changing the shape of a given array <br>
 `array.reshape(r,c)`
 5. _**Joining and splitting of arrays**_: Combining multiple arrays into one, and splitting one array into many <br>
 `np.vstack` `np.hstack` `np.tile`

In [ ]:
Image(filename='../images/np_broadcasting.png', width=800)

### 7. Using `lst` generate `arrint` as shown:

In [ ]:
lst = [1,2,3,4.0]

In [ ]:
array

### 8. Write a function to generate a list of all even numbers between 0 to 100

### 9. Write the same function as a list comprehension

### 10. For the above function, return the output as a 2D array with 2 rows

### 11. What are the different attributes of an array?

- ndims
- shape
- size
- dtype
- nbyter

### 12. Write 5 array generating functions: (like numpy.arange())

- np.random.randint
- np.ones
- np.zeros
- np.full
- np.eye
- np.linspace

### 13. From array `a`, create array `b` as a deep copy:

In [20]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b

In [23]:
b = a[1:3,1:3].copy()
b

array([[ 6,  7],
       [10, 11]])

### 14. Reshape arr into 2D array with 3 rows:

In [31]:
twoD_arr = np.arange(1, 46)

In [32]:
twoD_arr.reshape(3,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]])

- The criterion to satisfy for providing the new shape is that _'The new shape should be compatible with the original shape'_
- numpy allow us to give one of new shape parameter as -1 (eg: (2,-1) or (-1,3) but not (-1, -1)). 
- It simply means that it is an unknown dimension and we want numpy to figure it out. And numpy will figure this by looking at the 'length of the array and remaining dimensions' and making sure it satisfies the above mentioned criteria

### 15. From the array `twenty` below, generate the `result` as shown

In [ ]:
twenty = (np.arange(4 * 5)).reshape(4, 5)
twenty

In [ ]:
result

### 16. Using conditional statements, generate `result` from `range_arr` as shown:

In [33]:
range_arr = np.arange(0, 10, 0.5)
range_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [35]:
result

array([5.5, 6. , 6.5, 7. ])

In [42]:
idxs = (range_arr > 5) & (range_arr < 7.5)

In [43]:
idxs

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [44]:
result = range_arr[idxs]
result

array([5.5, 6. , 6.5, 7. ])

### 17. Using array `a` and `b`, create `vs` and `hs` as shown:

In [45]:
a = np.array([[1, 2], [3, 4]])
print(a.shape);a

(2, 2)


array([[1, 2],
       [3, 4]])

In [46]:
b = np.array([[5, 6]])
print(b.shape);b

(1, 2)


array([[5, 6]])

In [48]:
vs = np.vstack((a,b))
vs

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
vs

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
hs = np.hstack((a,b.T))
hs

array([[1, 2, 5],
       [3, 4, 6]])

In [50]:
hs

array([[1, 2, 5],
       [3, 4, 6]])

### 18. From the given array, generate row wise and column wise average as shown:

In [52]:
arr = np.arange(5 * 6).reshape(5, 6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [53]:
col_avg = arr.mean(axis=0) #column-wise
col_avg

array([12., 13., 14., 15., 16., 17.])

In [54]:
row_avg = arr.mean(axis=1) #row-wise
row_avg

array([ 2.5,  8.5, 14.5, 20.5, 26.5])

### 19. Show how to do this?

Suppose that X is a data matrix of shape `(n,p)`. That is, there are `n` data points and `p` features per point. Often, we have to remove the mean from each feature. That is, we want to compute the mean for each feature and then remove the mean from each column. 

In [61]:
# say n =10, and p =30
n = 10
p = 30
X = np.random.rand(n,p)
X.shape

(10, 30)

In [62]:
mean = X.mean(axis=0)

In [63]:
mean.shape

(30,)

In [69]:
right1 = X - mean

In [70]:
right = X - mean.reshape(1,30)

In [72]:
np.all(right1 == right)

True

### 20. Load the cars.csv as a dataframe.

In [73]:
file='../data/cars.csv'

In [81]:
cars = pd.read_csv(file, index_col=0)
cars.head(10)

Retail  Dealer  Engine  Cylinders  Horsepower  \
Name                                                                      
Acura 3.5 RL               43755   39014     3.5          6         225   
Acura 3.5 RL Navigation    46100   41100     3.5          6         225   
Acura MDX                  36945   33337     3.5          6         265   
Acura NSX S                89765   79978     3.2          6         290   
Acura RSX                  23820   21761     2.0          4         200   
Acura TL                   33195   30299     3.2          6         270   
Acura TSX                  26990   24647     2.4          4         200   
Audi A4 1.8T               25940   23508     1.8          4         170   
Audi A4 1.8T convertible   35940   32506     1.8          4         170   
Audi A4 3.0 convertible    42490   38325     3.0          6         220   

                          CityMPG  HighwayMPG  Weight  Wheelbase  Length  \
Name                                                                       
Acura 3.5 RL                   18          24    3880        115     197   
Acura 3.5 RL Navigation        18          24    3893        115     197   
Acura MDX                      17          23    4451        106     189   
Acura NSX S                    17          24    3153        100     174   
Acura RSX                      24          31    2778        101     172   
Acura TL                       20          28    3575        108     186   
Acura TSX                      22          29    3230        105     183   
Audi A4 1.8T                   22          31    3252        104     179   
Audi A4 1.8T convertible       23          30    3638        105     180   
Audi A4 3.0 convertible        20          27    3814        105     180   

                          Width  
Name                             
Acura 3.5 RL                 72  
Acura 3.5 RL Navigation      72  
Acura MDX                    77  
Acura NSX S                  71  
Acura RSX                    68  
Acura TL                     72  
Acura TSX                    69  
Audi A4 1.8T                 70  
Audi A4 1.8T convertible     70  
Audi A4 3.0 convertible      70

Retail  Dealer  Engine  Cylinders  Horsepower  \
Name                                                                     
Acura 3.5 RL              43755   39014     3.5          6         225   
Acura 3.5 RL Navigation   46100   41100     3.5          6         225   
Acura MDX                 36945   33337     3.5          6         265   

                         CityMPG  HighwayMPG  Weight  Wheelbase  Length  Width  
Name                                                                            
Acura 3.5 RL                  18          24    3880        115     197     72  
Acura 3.5 RL Navigation       18          24    3893        115     197     72  
Acura MDX                     17          23    4451        106     189     77

### 21. Using `loc` or `iloc` select the observation corresponding to `Audi A6 3.0` as a Series. The label of this row is `Audi A6 3.0` , the index is 15.

In [82]:
cars.loc["Audi A6 3.0"]

Retail        36640.0
Dealer        33129.0
Engine            3.0
Cylinders         6.0
Horsepower      220.0
CityMPG          20.0
HighwayMPG       27.0
Weight         3561.0
Wheelbase       109.0
Length          192.0
Width            71.0
Name: Audi A6 3.0, dtype: float64

In [83]:
cars.iloc[15]

Retail        36640.0
Dealer        33129.0
Engine            3.0
Cylinders         6.0
Horsepower      220.0
CityMPG          20.0
HighwayMPG       27.0
Weight         3561.0
Wheelbase       109.0
Length          192.0
Width            71.0
Name: Audi A6 3.0, dtype: float64

In [87]:
cars.Retail == cars["Retail"]

Name
Acura 3.5 RL                                  True
Acura 3.5 RL Navigation                       True
Acura MDX                                     True
Acura NSX S                                   True
Acura RSX                                     True
Acura TL                                      True
Acura TSX                                     True
Audi A4 1.8T                                  True
Audi A4 1.8T convertible                      True
Audi A4 3.0 convertible                       True
Audi A4 3.0                                   True
Audi A4 3.0 Quattro manual                    True
Audi A4 3.0 Quattro auto                      True
Audi A4 3.0 Quattro convertible               True
Audi A6 2.7 Turbo Quattro four-door           True
Audi A6 3.0                                   True
Audi A6 3.0 Avant Quattro                     True
Audi A6 3.0 Quattro                           True
Audi A6 4.2 Quattro                           True
Audi A8 L Quattro         

Indexing in Pandas can be done in 4 ways:
1.`[ ]` 2. ` . ` 3. `loc`  4. `iloc`

- With `loc` and `iloc` you can do practically any data selection operation on DataFrames. 
- `loc` is `label-based`, which means that you have to specify rows and columns based on their row and column labels. 
- `iloc` is `integer index based`, so you have to specify rows and columns by their integer index like you did in the previous exercise.

### 22. Load the `loans data.csv` into a dataframe. 
- Display the first 3 and last 3 rows. 
- Check no of data points,
- no of feature points corresponding to a given data point, 
- column labels, 
- columns dtypes, 

In [88]:
file='../data/loans data.csv'

In [90]:
ld = pd.read_csv(file)

In [91]:
ld.head(3)

ID Amount.Requested Amount.Funded.By.Investors Interest.Rate  \
0  81174.0            20000                      20000         8.90%   
1  99592.0            19200                      19200        12.12%   
2  80059.0            35000                      35000        21.98%   

  Loan.Length        Loan.Purpose Debt.To.Income.Ratio State Home.Ownership  \
0   36 months  debt_consolidation               14.90%    SC       MORTGAGE   
1   36 months  debt_consolidation               28.36%    TX       MORTGAGE   
2   60 months  debt_consolidation               23.81%    CA       MORTGAGE   

   Monthly.Income FICO.Range Open.CREDIT.Lines Revolving.CREDIT.Balance  \
0         6541.67    735-739                14                    14272   
1         4583.33    715-719                12                    11140   
2        11500.00    690-694                14                    21977   

   Inquiries.in.the.Last.6.Months Employment.Length  
0                             2.0          < 1 year  
1                             1.0           2 years  
2                             1.0           2 years

In [92]:
ld.tail(3)

ID Amount.Requested Amount.Funded.By.Investors Interest.Rate  \
2497  55610.0            10000                      10000        13.99%   
2498  38576.0             6000                       6000        12.42%   
2499   3116.0             9000                    5242.75        13.79%   

     Loan.Length        Loan.Purpose Debt.To.Income.Ratio State  \
2497   36 months  debt_consolidation                4.89%    PA   
2498   36 months      major_purchase               16.66%    NJ   
2499   36 months  debt_consolidation                6.76%    NY   

     Home.Ownership  Monthly.Income FICO.Range Open.CREDIT.Lines  \
2497       MORTGAGE         2166.67    680-684                 4   
2498           RENT         3500.00    675-679                 8   
2499           RENT         3875.00    670-674                 7   

     Revolving.CREDIT.Balance  Inquiries.in.the.Last.6.Months  \
2497                     4544                             0.0   
2498                        .                             0.0   
2499                     7589                             0.0   

     Employment.Length  
2497         10+ years  
2498           5 years  
2499         10+ years

In [93]:
ld.shape

(2500, 15)

In [94]:
ld.columns

Index(['ID', 'Amount.Requested', 'Amount.Funded.By.Investors', 'Interest.Rate',
       'Loan.Length', 'Loan.Purpose', 'Debt.To.Income.Ratio', 'State',
       'Home.Ownership', 'Monthly.Income', 'FICO.Range', 'Open.CREDIT.Lines',
       'Revolving.CREDIT.Balance', 'Inquiries.in.the.Last.6.Months',
       'Employment.Length'],
      dtype='object')

In [95]:
ld.dtypes

ID                                float64
Amount.Requested                   object
Amount.Funded.By.Investors         object
Interest.Rate                      object
Loan.Length                        object
Loan.Purpose                       object
Debt.To.Income.Ratio               object
State                              object
Home.Ownership                     object
Monthly.Income                    float64
FICO.Range                         object
Open.CREDIT.Lines                  object
Revolving.CREDIT.Balance           object
Inquiries.in.the.Last.6.Months    float64
Employment.Length                  object
dtype: object

### 23. In the `loans data` display all the unique types of Home.Ownership along with their total couts/frequency

In [96]:
ld["Home.Ownership"].head(10)

0    MORTGAGE
1    MORTGAGE
2    MORTGAGE
3    MORTGAGE
4        RENT
5         OWN
6        RENT
7    MORTGAGE
8        RENT
9        RENT
Name: Home.Ownership, dtype: object

In [99]:
ld["Home.Ownership"].unique()

array(['MORTGAGE', 'RENT', 'OWN', 'OTHER', 'NONE', nan], dtype=object)

In [101]:
ld["Home.Ownership"].value_counts()

MORTGAGE    1147
RENT        1146
OWN          200
OTHER          5
NONE           1
Name: Home.Ownership, dtype: int64

### 24. From the loans data, create a new csv with only `Home.Ownership` and  `Monthly.Income` as the cols. Also, select only the data points which have `Home.Ownership == MORTGAGE` and `Monthly.Income > 5000`

In [105]:
condition = (ld["Home.Ownership"] == "MORTGAGE")&(ld["Monthly.Income"]>5000)

In [106]:
desired_cols = ["Home.Ownership","Monthly.Income"]

In [107]:
ld.loc[condition, desired_cols]

Home.Ownership  Monthly.Income
0          MORTGAGE         6541.67
2          MORTGAGE        11500.00
7          MORTGAGE        13863.42
12         MORTGAGE        14166.67
20         MORTGAGE         6666.67
21         MORTGAGE         6250.00
30         MORTGAGE         5833.33
31         MORTGAGE        10583.33
32         MORTGAGE        10416.67
35         MORTGAGE         5583.33
47         MORTGAGE        11250.00
58         MORTGAGE         5166.67
61         MORTGAGE         8000.00
79         MORTGAGE         5416.67
80         MORTGAGE         5883.33
81         MORTGAGE         5833.33
85         MORTGAGE         6666.67
91         MORTGAGE         6000.00
94         MORTGAGE         5250.00
95         MORTGAGE        10000.00
96         MORTGAGE        10000.00
97         MORTGAGE        12500.00
99         MORTGAGE         5833.33
104        MORTGAGE         7083.33
106        MORTGAGE        14583.33
111        MORTGAGE         9583.33
114        MORTGAGE        12916.67
118        MORTGAGE         6000.00
120        MORTGAGE         6250.00
123        MORTGAGE         9000.00
...             ...             ...
2412       MORTGAGE        12500.00
2413       MORTGAGE         9583.33
2414       MORTGAGE        10737.50
2422       MORTGAGE         5666.67
2429       MORTGAGE         6000.00
2440       MORTGAGE         5833.00
2441       MORTGAGE         9750.00
2444       MORTGAGE        11666.67
2446       MORTGAGE         5641.67
2447       MORTGAGE         6000.00
2453       MORTGAGE         5900.00
2454       MORTGAGE         6250.00
2455       MORTGAGE         5577.26
2460       MORTGAGE        19583.33
2462       MORTGAGE         9166.67
2468       MORTGAGE         6333.00
2469       MORTGAGE         6125.00
2471       MORTGAGE         5166.67
2472       MORTGAGE         5500.00
2476       MORTGAGE         8583.33
2477       MORTGAGE        25000.00
2478       MORTGAGE         5416.67
2481       MORTGAGE         9250.00
2482       MORTGAGE         7075.50
2484       MORTGAGE         6666.67
2485       MORTGAGE         7083.33
2492       MORTGAGE         5166.67
2493       MORTGAGE         7083.33
2494       MORTGAGE         6666.67
2495       MORTGAGE         9250.00

[686 rows x 2 columns]

### 25. In the previous data, for each Home Ownership type calculate the mean monthly income

In [108]:
ld.groupby("Home.Ownership")["Monthly.Income"].mean()

Home.Ownership
MORTGAGE    6628.321126
NONE                NaN
OTHER       5569.934000
OWN         4771.817350
RENT        4910.075590
Name: Monthly.Income, dtype: float64

### 26. In the loans data, identify column that has highest no of missing values

In [111]:
ld.isnull().sum(axis=0)

ID                                 1
Amount.Requested                   1
Amount.Funded.By.Investors         1
Interest.Rate                      0
Loan.Length                        1
Loan.Purpose                       1
Debt.To.Income.Ratio               1
State                              1
Home.Ownership                     1
Monthly.Income                     3
FICO.Range                         0
Open.CREDIT.Lines                  4
Revolving.CREDIT.Balance           3
Inquiries.in.the.Last.6.Months     3
Employment.Length                 78
dtype: int64

### 27. From the previous question, remove all data points that have missing values corresponding to the column you have identified.

In [115]:
s= ld.dropna()

In [116]:
s.isnull().sum(axis=0)

ID                                0
Amount.Requested                  0
Amount.Funded.By.Investors        0
Interest.Rate                     0
Loan.Length                       0
Loan.Purpose                      0
Debt.To.Income.Ratio              0
State                             0
Home.Ownership                    0
Monthly.Income                    0
FICO.Range                        0
Open.CREDIT.Lines                 0
Revolving.CREDIT.Balance          0
Inquiries.in.the.Last.6.Months    0
Employment.Length                 0
dtype: int64

In [113]:
r = ld.dropna(subset=["Employment.Length"])

In [114]:
r.isnull().sum(axis=0)

ID                                1
Amount.Requested                  1
Amount.Funded.By.Investors        1
Interest.Rate                     0
Loan.Length                       1
Loan.Purpose                      1
Debt.To.Income.Ratio              1
State                             1
Home.Ownership                    1
Monthly.Income                    3
FICO.Range                        0
Open.CREDIT.Lines                 4
Revolving.CREDIT.Balance          3
Inquiries.in.the.Last.6.Months    3
Employment.Length                 0
dtype: int64

## Bonus Questions

## 1. Compute Eigen Value and Eigen Vectors

 - Every vector (list of numbers) has a direction when it is plotted on a XY chart.
 
 - Consider A to be any square matrix. Now, almost all vectors will change direction, when they are multiplied by A. Certain exceptional vectors x are in the same direction as Ax, i.e. the direction of x and Ax will be the same. Those are the “eigenvectors”. Multiply an eigenvector by A, and the vector Ax is a number () times the original x. The number () is called the "eigenvalue".
 
 - An eigenvector is a vector whose direction remains unchanged when a linear transformation is applied to it.
 
 - Eigen value— The scalar that is used to transform an Eigenvector.
 
 - The eigenvalue tells whether the special vector x is stretched or shrunk or reversed or left unchanged—when it is multiplied by A. 

`A * eigen_vector — eigen_value * eigen_vector = 0`

In [ ]:
arr = np.arange(0,9).reshape(3,3)
arr

### 2. Write a Python class named Circle constructed by a radius and two methods which will compute the area and the perimeter of a circle.

### 3. Write a function to convert a list to dictionary as shown: 

`mylist = ['Zero', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine']`

`mydict = 
{
    0 : 'Zero',
    1 : 'One',
    2 : 'Two',
    3 : 'Three',
    4 : 'Four',
    5 : 'Five',
    6 : 'Six',
    7 : 'Seven',
    8 : 'Eight',
    9 : 'Nine',
}`

In [ ]:
x = ['Zero', 'One', 'Two', 'Three', 'Four']

In [ ]:
d = list_to_dict(x)
d

### 3. Binary Search

Given a sorted array arr[] of n elements, write a function to search a given element x in arr[].

A simple approach is to do linear search.The time complexity of above algorithm is O(n). Another approach to perform the same task is using Binary Search. 

In Binary search, we search a sorted array by repeatedly dividing the search interval in half. Begin with an interval covering the whole array. If the value of the search key is less than the item in the middle of the interval, narrow the interval to the lower half. Otherwise narrow it to the upper half. Repeatedly check until the value is found or the interval is empty.

In [ ]:
# Test array 
arr = [ 2, 3, 4, 10, 40 ] 
x = 10
  
# Function call 
result = binarySearch(arr, 0, len(arr)-1, x) 
  
if result != -1: 
    print("Element is present at index %d" % result)
else: 
    print("Element is not present in array")

### 4. Given a list of numbers, write a function to return outliers?

#### How are outliers defined?

Here we can assume that outliers are defined as numbers outside of `[Q1 - 1.5 * IQR, Q3 + 1.5 * IQR]`
where `Q1` is the first quartile, `Q3` is the third quartile, and `IQR` is the inner quartile range `(Q3 - Q1)`

The runtime of this algorithm is at least O(n), but potentially larger depending on how numpy computes quartiles.

In [ ]:
L = [1,2,3,4,6,1,2,3,4,6,1,99,-100,1,2,3,4,5,2,2,22,34,1,2,3,4,-10]
findOutliers(L)